=head1 Welcome to Perltidy!

Perltidy is a tool to indent and reformat perl scripts.

Perltidy is free software released under the GNU General Public
License -- please see the included file "COPYING" for details.

There are two source distribution files, a F<.tgz> "tarball" for unix
systems and a zip file, F<.zip> for Windows.  The only differences is
that the line endings have been changed to <cr><lf> for the Windows
version.

Besides the source distribution files, a set of test files is available
in a separate package (but there is no automated test procedure yet).
These are distributed separately because they will not be of interest to
the average user.  If you do want the test files, you should untar or
unzip them at the same directory that you untar or unzip the source files.

Please see the ChangeLog file for notices of any recent updates.

Please see the BUGS file for a list of all known open bugs.

=head1 INSTALLATION

Please see the file INSTALL for installation information.

=head1 WHAT NEXT

Documentation can be found in the F<docs> directory, and it can also be 
found at http://perltidy.sourceforge.net

Reading the brief tutorial should help you use Perltidy effectively.  

Perltidy is still being developed, so please check sourceforge occasionally
for updates if you find that it is useful.  New releases are announced
on freshmeat.net.

=head1 FEEDBACK / BUG REPORTS

If you see ways to improve this document for the particular system on
which you install Perltidy, please let the me know so that it can be
updated.

Bug reports, comments and suggestions are welcome.  Attach the smallest
piece of code which demonstrates the bug or issue, plus a .LOG file from
a Perltidy run, if appropriate.  Your efforts are greatly appreciated!

Thank You

 Steve Hancock
 perltidy at users.sourceforge.net
 http://perltidy.sourceforge.net

