=head1 Perltidy TODO List

This is a "wish-list" of features to add and things to do.  

=head2 Fix numerous little formatting issues

There is (and always will be) a large backlog of little formatting
issues in which the formatting could be better.  These are things like
improving line break choices and improving vertical alignment.  I'm
working on them as time permits, with priority given to items that are
of interest to perltidy users.

=head2 Option to reformat block comments

A future option should use Text::Autoformat to reformat block comments.
Thanks to Tim Maher for this suggestion.

=head2 Improved Vertical Alignment

Coding modifications are underway to enhance the vertical alignment.

=head2 BUGS

There are still a couple of bugs listed in the BUGS file that need
to be fixed.  These are low priority compared to formatting
issues, but need to be done.

=head2 Automated testing

An automated method for testing many combinations of parameter options 
on a variety of test files would be very helpful.

=head2 Documentation

A FAQ or maybe COOKBOOK needs to be written, to explain some of the
more subtle formatting issues.

=head2 Tokenization issues

It would be nice to introduce some more token types, such as procedure
calls, so that they can be given separate colors in html files.  

There are some subtle issues with distinguishing block types that should
be addressed to make the tokenizer more correct, even though
they do not interfere with code beautification.

=head2 Modularization

It is planned to release perltidy in modules, hopefully this year.
However, the development of the tokenizer and formatter is still very
tightly coupled, and there are still some open tokenization issues that
need to be resolved before the program is split into pieces.  Anyone is
welcome, of course, to extract the tokenizer and use it for other
projects, but it would be good to let me know so that we can coordinate
updates to the tokenizer.
