#!/usr/bin/env perl

package main;

##BEGIN:REMOVE BEFORE PACKAGING#############################
BEGIN {
    unshift @INC, '/home/steve/src/perldev/perltidy/src';
}
##END:REMOVE BEFORE PACKAGING###############################
use Perl::Tidy;

# remove any temporary files if interrupted
$SIG{INT} = sub {
    Perl::Tidy::interrupt_handler();
    exit -1;
};

Perl::Tidy::perltidy(
    source      => undef,
    destination => undef,
    stderr      => undef,
    argv        => undef,
);
