#!/usr/bin/env perl
package main;

##BEGIN:REMOVE BEFORE PACKAGING#############################
BEGIN {
    unshift @INC, '/home/steve/src/perldev/perltidy/src';
}
##END:REMOVE BEFORE PACKAGING###############################
use Perl::Tidy;

# remove any temporary files if interrupted
$SIG{INT} = sub { Perl::Tidy::interrupt_handler(-1) };

Perl::Tidy::perltidy();
