#!/usr/bin/env perl

package main;

##BEGIN:REMOVE BEFORE PACKAGING#############################
BEGIN {
    unshift @INC, '/home/steve/src/perldev/perltidy/src';
}
##END:REMOVE BEFORE PACKAGING###############################
use PerlTidy;

# remove any temporary files if interrupted
$SIG{INT} = sub {
    print STDERR "perltidy interrupted\n";
    PerlTidy::cleanup();
    exit -1;
};

PerlTidy::perltidy(
    source      => undef,
    destination => undef,
    stderr      => undef,
    argv        => undef,
);
